Repository abhay-raj19/FitBody, pull requests merged in 2023-10, with the labels that each got.

#11 Feature/#10 enhance btn effect
  src/components/Header/Header.jsx
  src/components/UI/Footer.jsx
  src/styles/footer.css
  src/styles/header.css
Labels: hacktoberfest

#20 made navbar responsive and added effects
  src/components/Header/Header.jsx
  src/styles/header.css
Labels: hacktoberfest-accepted

#24 Fixed overflow
  src/styles/hero.css
Labels: hacktoberfest-accepted

#25 Refactored the hero section
  src/components/UI/Hero.jsx
  src/styles/hero.css
Labels: hacktoberfest-accepted

#35 Implement Dark Mode Feature- Fixes #7
  src/App.css
  src/App.js
  src/components/Header/Header.jsx
  src/components/UI/Hero.jsx
  src/styles/exercises.css
  src/styles/footer.css
  src/styles/header.css
  src/styles/hero.css
  src/styles/pricing.css
  src/styles/start.css
Labels: hacktoberfest-accepted

#36 Removed excessive right padding in mobile view - fixes #34
  public/index.html
  src/App.css
Labels: hacktoberfest, hacktoberfest-accepted

#46 Fix/nav transp
  src/styles/header.css
Labels: hacktoberfest, hacktoberfest-accepted

#59 Fix/testimonial spacing
  src/components/Header/Header.jsx
  src/styles/header.css
  src/styles/testimonials.css
Labels: hacktoberfest, hacktoberfest-accepted

#60 Added the social media handles
  src/components/UI/Footer.jsx
  src/styles/footer.css
Labels: hacktoberfest-accepted

#68 added form validation
  src/components/UI/ContactUs.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#65 Fixed dark mode compatibilty of footer
  src/styles/footer.css
Labels: hacktoberfest, hacktoberfest-accepted

#72 changed toggle button Color
  src/styles/header.css
Labels: hacktoberfest, hacktoberfest-accepted

#78 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
