Repository abhay-raj19/FitBody, pull requests merged in 2024-05, with the labels that each got.

#136 Add fix to footer dark mode
  src/App.js
  src/styles/footer.css
Labels: enhancement, GSsoC'24, Level 1

#143 making the new contributors profile automatically added
  README.md
Labels: enhancement, wontfix, gssoc, level3

#201 Added card hovering effect for pricing section #172
  index.html
  package-lock.json
  package.json
  style.css
Labels: gssoc, level1, conflicts

#170 Added validations using react-toastify
  package-lock.json
  package.json
  src/components/UI/ContactUs.jsx
Labels: gssoc, level1, conflicts

#247 addition_issue_template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/document.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/refactor_code.yml
Labels: enhancement, gssoc, level3

#227 Added cursor effect
  index.html
  public/cursor.js
  src/styles/cursor.css
Labels: enhancement, gssoc, level3

#257 testimonial images changed
  src/assets/img/testinomial01.jpeg
  src/assets/img/testinomial02.jpg
  src/assets/img/testinomial03.jpg
  src/assets/img/testinomial04.jpg
  src/assets/img/testinomial05.jpg
  src/components/UI/Testimonials.jsx
  src/styles/testimonials.css
Labels: enhancement, gssoc, level3
